#!/usr/bin/env bash

set -euo pipefail

name="${1}"
message="${2}"
reason="${3}"
canceler="${4}"
printfile=/tmp/DEVTERM_PRINTER_IN

echo " " > "$printfile"
echo "==================================" > "$printfile"
echo "ERROR :: WINDMILL.VRAI.DEV" > "$printfile"
echo "$(date)" > "$printfile"
echo "==================================" > "$printfile"
echo "name:" > "$printfile"
echo "$name" > "$printfile"
echo " " > "$printfile"
echo "message:" > "$printfile"
echo "$message" > "$printfile"
echo " " > "$printfile"
echo "reason:" > "$printfile"
echo "$reason" > "$printfile"
echo " " > "$printfile"
echo "canceler:" > "$printfile"
echo "$canceler" > "$printfile"
echo "==================================" > "$printfile"
echo " " > "$printfile"
echo " " > "$printfile"
echo " " > "$printfile"
echo " " > "$printfile"
echo " " > "$printfile"
echo " " > "$printfile"
echo " " > "$printfile"
